apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-docker-app
  template:
    metadata:
      labels:
        app: my-docker-app
    spec:
      containers:
      - name: my-docker-app
        image: asia-south1-docker.pkg.dev/internal-sandbox-446612/my-docker-repo/my-docker-app:latest
        ports:
          - containerPort: 5000
