apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudambassadors-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudambassadors-app
  template:
    metadata:
      labels:
        app: cloudambassadors-app
    spec:
      containers:
      - name: app
        image: asia-south1-docker.pkg.dev/internal-sandbox-446612/cloudambassadors-repo/app:latest
        ports:
        - containerPort: 5000
